# Generated by Django 4.2.2 on 2023-12-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(max_length=200),
        ),
    ]
