# Generated by Django 4.2.2 on 2023-12-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_likes_alter_post_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='author',
        ),
    ]
